{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "horo-storage.fullname" . }}
  labels:
    {{- include "horo-storage.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.ui_path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "horo-storage.fullname" $ }}-ui
                port:
                  number: {{ $.Values.service.ui.port }}
          - path: {{ .Values.ingress.api_path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "horo-storage.fullname" $ }}-api
                port:
                  number: {{ $.Values.service.api.port }}
{{- end }}
